export type SituacaoRegistro = "ativo" | "pausado" | "encerrado";

export type RegistroMockSeed = {
  id: string;
  demanda: string;
  cliente: string;
  centroCusto: string;
  preposto: string;
  gerente: string;
  sigla: string;
  tipoServico: string;
  metodologia: string;
  situacao: SituacaoRegistro;
};

/** Dados sintéticos para exercitar Badge e Pagination na página de registros */
export const SEED_REGISTROS: RegistroMockSeed[] = [
  {
    id: "seed-1",
    demanda: "Registro Alfa — integração QA",
    cliente: "Cliente A",
    centroCusto: "Categoria A",
    preposto: "Ana Martins",
    gerente: "Responsável A",
    sigla: "RAL-001",
    tipoServico: "Operação",
    metodologia: "Scrum",
    situacao: "ativo",
  },
  {
    id: "seed-2",
    demanda: "Checklist entrega modelo",
    cliente: "Cliente B",
    centroCusto: "Categoria B",
    preposto: "Bruno Nunes",
    gerente: "Responsável B",
    sigla: "CDE-042",
    tipoServico: "Análise",
    metodologia: "Kanban",
    situacao: "pausado",
  },
  {
    id: "seed-3",
    demanda: "Homologação de fluxo lateral",
    cliente: "Cliente C",
    centroCusto: "Categoria C",
    preposto: "",
    gerente: "Responsável C",
    sigla: "HOM-883",
    tipoServico: "Acompanhamento",
    metodologia: "Híbrido",
    situacao: "ativo",
  },
  {
    id: "seed-4",
    demanda: "Preparação de ambiente WT",
    cliente: "Cliente A",
    centroCusto: "Categoria A",
    preposto: "Carla Dias",
    gerente: "Responsável A",
    sigla: "PWD-221",
    tipoServico: "Operação",
    metodologia: "Kanban",
    situacao: "encerrado",
  },
  {
    id: "seed-5",
    demanda: "Reunião técnica de alinhamento",
    cliente: "Cliente D",
    centroCusto: "Categoria B",
    preposto: "",
    gerente: "Responsável B",
    sigla: "RTA-110",
    tipoServico: "Análise",
    metodologia: "Lean",
    situacao: "ativo",
  },
  {
    id: "seed-6",
    demanda: "Validação UX mock",
    cliente: "Cliente E",
    centroCusto: "Categoria C",
    preposto: "Diego Ramos",
    gerente: "Responsável C",
    sigla: "VXU-014",
    tipoServico: "Acompanhamento",
    metodologia: "Scrum",
    situacao: "pausado",
  },
  {
    id: "seed-7",
    demanda: "Correções pós-feedback",
    cliente: "Cliente B",
    centroCusto: "Categoria A",
    preposto: "",
    gerente: "Responsável A",
    sigla: "CFB-907",
    tipoServico: "Operação",
    metodologia: "XP",
    situacao: "ativo",
  },
  {
    id: "seed-8",
    demanda: "Documentação inicial",
    cliente: "Cliente C",
    centroCusto: "Categoria B",
    preposto: "",
    gerente: "Responsável B",
    sigla: "DOC-055",
    tipoServico: "Análise",
    metodologia: "Waterfall",
    situacao: "encerrado",
  },
  {
    id: "seed-9",
    demanda: "Pipeline de relatórios",
    cliente: "Cliente A",
    centroCusto: "Categoria C",
    preposto: "Elias Prado",
    gerente: "Responsável C",
    sigla: "PIP-664",
    tipoServico: "Operação",
    metodologia: "Safe",
    situacao: "ativo",
  },
  {
    id: "seed-10",
    demanda: "Diagnóstico de permissões",
    cliente: "Cliente D",
    centroCusto: "Categoria A",
    preposto: "",
    gerente: "Responsável A",
    sigla: "DPS-773",
    tipoServico: "Acompanhamento",
    metodologia: "Scrum",
    situacao: "pausado",
  },
  {
    id: "seed-11",
    demanda: "Backlog semanal",
    cliente: "Cliente E",
    centroCusto: "Categoria B",
    preposto: "",
    gerente: "Responsável B",
    sigla: "BLK-331",
    tipoServico: "Operação",
    metodologia: "Kanban",
    situacao: "ativo",
  },
  {
    id: "seed-12",
    demanda: "Simulação de carga WT",
    cliente: "Cliente B",
    centroCusto: "Categoria C",
    preposto: "Fátima Luz",
    gerente: "Responsável C",
    sigla: "SLC-902",
    tipoServico: "Análise",
    metodologia: "Lean",
    situacao: "encerrado",
  },
  {
    id: "seed-13",
    demanda: "Check de acessibilidade",
    cliente: "Cliente C",
    centroCusto: "Categoria A",
    preposto: "",
    gerente: "Responsável A",
    sigla: "ACC-045",
    tipoServico: "Acompanhamento",
    metodologia: "Híbrido",
    situacao: "ativo",
  },
  {
    id: "seed-14",
    demanda: "Importação CSV teste",
    cliente: "Cliente A",
    centroCusto: "Categoria B",
    preposto: "",
    gerente: "Responsável B",
    sigla: "CSV-661",
    tipoServico: "Operação",
    metodologia: "Scrum",
    situacao: "pausado",
  },
  {
    id: "seed-15",
    demanda: "Curadoria de conteúdo",
    cliente: "Cliente D",
    centroCusto: "Categoria C",
    preposto: "Gabriel Dias",
    gerente: "Responsável C",
    sigla: "CNT-772",
    tipoServico: "Análise",
    metodologia: "Kanban",
    situacao: "ativo",
  },
  {
    id: "seed-16",
    demanda: "Playbook onboarding",
    cliente: "Cliente E",
    centroCusto: "Categoria A",
    preposto: "",
    gerente: "Responsável A",
    sigla: "ONB-120",
    tipoServico: "Acompanhamento",
    metodologia: "Safe",
    situacao: "encerrado",
  },
  {
    id: "seed-17",
    demanda: "Rotina métricas simuladas",
    cliente: "Cliente B",
    centroCusto: "Categoria B",
    preposto: "",
    gerente: "Responsável B",
    sigla: "MET-448",
    tipoServico: "Operação",
    metodologia: "XP",
    situacao: "ativo",
  },
];
